### ISSUE TITLE
Reporting config input support

### ISSUE THREAD

**Issue by 0xcrypto** [projectdiscovery/nuclei-action#14]
So I installed pd-actions, configured github issue reporting for nuclei but then I was flooded with `info` reports. So I added info to deny list in the bug-tracker-config.yaml and used `config` input for nuclei-action in pd-actions.yaml. But the nuclei-action tried to copy config file and the action died with error:

```
cp: cannot create regular file '/.config/nuclei/config.yaml': No such file or directory
```

**Comment by ehsandeep** [comment]
@0xcrypto can you share the action file snippet that uses nuclei?

**Comment by 0xcrypto** [comment]
```
      - name: Nuclei Scan
        uses: projectdiscovery/nuclei-action@main
        with:
          urls: output/active_urls.txt
          # templates: custom_templates
          github-report: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output: output/nuclei_output.txt
          config: config/bug-tracker-config.yaml
```
