### ISSUE TITLE
Failed to find templates.

### ISSUE THREAD

**Issue by random-robbie** [projectdiscovery/nuclei-action#18]
Does the action need updating?

pd-actions.yaml
---
```
      - name: Nuclei Scan
        uses: projectdiscovery/nuclei-action@main
        with:
          urls: output/active_urls.txt
          output: output/nuclei_output.txt
          
```

Github Log
---
```
Run projectdiscovery/nuclei-action@main
  with:
    urls: output/active_urls.txt
    output: output/nuclei_output.txt
    json: false
    include-rr: false
    github-report: false
  env:
    GOROOT: /opt/hostedtoolcache/go/1.14.15/x64
[FTL] Program exiting: no template/templates provided
```

**Comment by toufik-airane** [comment]
Dear @random-robbie,

You should run a checkout stage before running a nuclei action.
The checkout command enables working with files stored in the repository.

Here is an example of a full workflow:

```
jobs:
  nuclei-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 <--- this is the checkout stage

      - uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Nuclei Scan
        uses: projectdiscovery/nuclei-action@main
        with:
          urls: output/active_urls.txt
          output: output/nuclei_output.txt

      - name: GitHub Workflow artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nuclei.log
          path: output/nuclei_output.txt
```

Feel free to ping me on Discord if you need any onboarding.

Best regards.
