### ISSUE TITLE
v2.3.1 compat

### ISSUE THREAD

**Issue by revolunet** [projectdiscovery/nuclei-action#5]
Hi, i've setup the action on a new repo and looks like the action doesnt work anymore with nuclei 2.3.1. Same action code still works in old repo 🤔 

It downloads a bunch of templates but ends with 

```
Nuclei Templates v8.1.5 Changelog
[INF] Successfully downloaded nuclei-templates (v8.1.5). Enjoy!
+-------+-------+---------+
| TOTAL | ADDED | REMOVED |
+-------+-------+---------+
|   738 |   738 |       0 |
+-------+-------+---------+
cp: cannot create regular file 'nuclei-templates/.nuclei-ignore': No such file or directory
Error: Process completed with exit code 1.
```

**Comment by revolunet** [comment]
So the latest docker image is 2.3.0 apparently

i had to change the action like this :
```sh
        mkdir nuclei-templates
        nuclei -ut -ud ./nuclei-templates
        nuclei \
          -l ${{ inputs.urls }} \
          -t ./nuclei-templates \
          -o ${{ inputs.output }} \
          -H "User-Agent: ${{ inputs.user-agent }}" \
          -json \
          -include-rr \
          \
```

**Comment by fguisso** [comment]
I think that the problem is the `--update-directory` because in the master branch the config sets to `./`.

Can you update the master with your code?

**Comment by Gowiem** [comment]
@revolunet @fguisso I'm seeing the error when using `templates: "./"`

```
Nuclei Templates v8.1.7 Changelog
|   824 |   824 |       0 |
+-------+-------+---------+
[INF] Successfully downloaded nuclei-templates (v8.1.7). Enjoy!
cp: '.nuclei-ignore' and './/.nuclei-ignore' are the same file
```

Did either of you get that working? Is this just a blocker bug to use this action at all currently?

**Comment by fguisso** [comment]
You need to use the .nuclei-ignore or set `false`, this is my working sample:
```yaml
name: Nuclei workflow

on:
  workflow_dispatch:
    #schedule:
    #- cron: "0 10 * * *"

jobs:
  nuclei-worker:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache
        with:
          path: /home/runner/go/bin/nuclei
          key: ${{ runner.os }}-${{ hashFiles('/home/runner/go/bin/nuclei') }}

      - uses: projectdiscovery/nuclei-action@main
        with:
          user-agent: true
          urls: "urls.txt"
          templates: "./"
          nuclei-ignore: false
          output: "nuclei.log"

      - uses: actions/upload-artifact@v2
        with:
          name: nuclei.log
          path: nuclei.log
```
