### ISSUE TITLE
Duplicate GitHub issues prevention

### ISSUE THREAD

**Issue by rotemreiss** [projectdiscovery/nuclei-action#60]
I'm using the action with custom templates and the option to report findings as GitHub issues. 
The issue is that every time my workflow runs (e.g., on push) new issues on the same findings are being created.
Is it possible to not open new issues if an issue already exists? If not, this should only be used on releaae, or what is the optimal trigger for such a workflow?

**Comment by forgedhallpass** [comment]
I've created a ticket that would cover this. You can track it here:
https://github.com/projectdiscovery/nuclei/issues/3429

**Comment by dogancanbakir** [comment]
Closing this since this feature is now available for use.

**Comment by monizb** [comment]
@dogancanbakir I tried using this on my repo and setting update-existing to true under github, it still seems to create a new issue for every existing issue, here is my reporting config:

```
allow-list:
  severity: info, low, high, critical, medium

# GitHub contains configuration options for GitHub issue tracker
github:
  # issue-label is the label of the created issue type
  issue-label: security
  # update-existing is the boolean which tells if the existing, opened issue should be updated or new one should be created
  update-existing: true
  # duplicate-issue-check flag to enable duplicate tracking issue check.
  duplicate-issue-check: true
  # username of the github accont being used
  username: user
  # token is the token for GitLab account
  token: test-token
  # project-name is the name/id of the project(repository)
  project-name: "1234"
```
