### ISSUE TITLE
Scan fails intermittently 

### ISSUE THREAD

**Issue by rxerium** [projectdiscovery/nuclei-action#65]
Hello, below is the error I am receiving:

```
[0:51:35] | Templates: 211 | Hosts: 2510 | RPS: 95 | Matched: 0 | Errors: 27076 | Requests: 294794/973880 (30%)
[0:51:40] | Templates: 211 | Hosts: 2510 | RPS: 95 | Matched: 0 | Errors: 27085 | Requests: 294803/973880 (30%)
[0:51:45] | Templates: 211 | Hosts: 2510 | RPS: 94 | Matched: 0 | Errors: 27100 | Requests: 294891/973880 (30%)
/home/ubuntu/rishi/_work/_actions/projectdiscovery/nuclei-action/main/dist/index.js:1598
                error = new Error(`The process '${this.toolPath}' failed with exit code ${this.processExitCode}`);
                        ^

Error: The process '/home/ubuntu/rishi/_work/_temp/84a23889-b3e1-4cf5-b971-0f06c245741a/nuclei' failed with exit code null
    at ExecState._setResult (/home/ubuntu/rishi/_work/_actions/projectdiscovery/nuclei-action/main/dist/index.js:1598:25)
    at ExecState.CheckComplete (/home/ubuntu/rishi/_work/_actions/projectdiscovery/nuclei-action/main/dist/index.js:1581:18)
    at ChildProcess.<anonymous> (/home/ubuntu/rishi/_work/_actions/projectdiscovery/nuclei-action/main/dist/index.js:1475:27)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Socket.<anonymous> (node:internal/child_process:458:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:301:12)
```
My workflow starts off with httpx Action then outputs it to Nuclei Action. After running it through httpx action I have 2510 hosts (the error still occurs even when not using httpx in the workflow). My Github Action Workflow file is:

```
      - name: httpX Scan
        uses: projectdiscovery/httpx-action@main
        with:
          list: .github/input/Globe.txt
          flags: "-config .github/configurations/httpx/httpx-config.yaml"

      - name: Nuclei Scan
        uses: projectdiscovery/nuclei-action@main
        with:
          urls: httpx.log
          output: /home/ubuntu/OutputFiles/Globe-Scan1-output.txt
          config: .github/configurations/nuclei/main-config.yaml
```

And the Nuclei config is:
```# Tags based template execution
tags: kev

# Optimisations
scan-strategy: host-spray
concurrency: 200
bulk-size: 10
max-host-error: 5
max-redirects: 1

# Misc
stats: true
ts: true```

Happy to provide more info if needed.

Thanks

Rishi
