### ISSUE TITLE
[Feature Request] Support Template URLs

### ISSUE THREAD

**Issue by pbnj-dragon** [projectdiscovery/nuclei-action#72]
Supporting template URLs should relatively simple to introduce.

Example:

```yaml
      - name: Nuclei - Vulnerability Scan
        uses: projectdiscovery/nuclei-action@main
        with:
          target: https://example.com
          templates: https://raw.githubusercontent.com/foo/bar/main/custom-templates.yml
```

In `index.js`, something like this perhaps:

```js
if (templates) {
  try {
    # URL() constructor will throw if a string is not URL, per https://www.rfc-editor.org/rfc/rfc3986
    new URL(templates)
    params.push(`-turl=${templates}`);
  } catch () {
    params.push(`-t=${templates}`);
  }
}
```
