### ISSUE TITLE
 Error: Error writing the report config file: EISDIR: illegal operation on a directory

### ISSUE THREAD

**Issue by aminvakil** [projectdiscovery/nuclei-action#89]
This config does not work and breaks with this error:
```
      - name: Nuclei Scan
        uses: projectdiscovery/nuclei-action@main
        with:
          urls: output/active_urls.txt
          output: output/nuclei_output.txt
          flags: "-exclude-id http-missing-security-headers"
```
```
Error: Error writing the report config file: EISDIR: illegal operation on a directory, open '/home/runner/work/pd-actions/pd-actions'
```
Unfortunately repository is private and I cannot share url to GHA.

I don't use it daily, but last time it worked was three months ago.
