### ISSUE TITLE
`serif_exists` output not returing true

### ISSUE THREAD

**Issue by brettcurtis** [projectdiscovery/nuclei-action#95]
I'm not sure this is working anymore (based off the README.md):

```none
        if: steps.nuclei_scan.outputs.sarif_exists == 'true'
```

Regardless this is skipped. 

Here is an example:

This should have ran: https://github.com/osinfra-io/google-cloud-kubernetes/actions/runs/14316089159/job/40122413889

**Comment by dogancanbakir** [comment]
I couldn't repro this issue. This is the setup I used to debug it:

```yaml
name: Nuclei - Vulnerability Scan

on:
  push:
  workflow_dispatch:

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Nuclei - Vulnerability Scan
        id: nuclei_scan
        uses: projectdiscovery/nuclei-action@main
        with:
          target: https://example.com

      - name: Debug sarif_exists
        run: 'echo "sarif_exists: ${{ steps.nuclei_scan.outputs.sarif_exists }}"'

      - name: GitHub Workflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nuclei.log
          path: nuclei.log

      - name: GitHub Security Dashboard Alerts update
        if: steps.nuclei_scan.outputs.sarif_exists == 'true'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: nuclei.sarif
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

<img width="356" alt="Image" src="https://github.com/user-attachments/assets/247ce843-60e8-4f1e-9cb9-3ea7672a33f4" />

Pls ignore the err since it's specific to my private repo:
<img width="1404" alt="Image" src="https://github.com/user-attachments/assets/c612c4f5-e5c9-483b-a547-2c198bc70bfd" />
